// <auto-generated />
using System;
using Elearning.API.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elearning.API.Migrations.Database
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251226123144_RemoveCourseCompletion")]
    partial class RemoveCourseCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elearning.API.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AnnouncementId")
                        .HasName("PK__Announce__9DE445746CD3C3A8");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "IsPublished" }, "IX_Announcement_IsPublished");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("Elearning.API.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBD3CC905CA");

                    b.HasIndex(new[] { "EntityId" }, "IX_AuditLog_EntityId");

                    b.HasIndex(new[] { "EntityName" }, "IX_AuditLog_EntityName");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditLog_UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Elearning.API.Models.CertificateTemplate", b =>
                {
                    b.Property<int>("CertificateTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateTemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CertificateTemplateId")
                        .HasName("PK__Certific__E97CFAABF51B323B");

                    b.ToTable("CertificateTemplate");
                });

            modelBuilder.Entity("Elearning.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CourseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<int?>("ThumbnailMediaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TutorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D71A783A0950D");

                    b.HasIndex("ThumbnailMediaId");

                    b.HasIndex("TutorUserId");

                    b.HasIndex(new[] { "CourseCategoryId" }, "IX_Course_CategoryId");

                    b.HasIndex(new[] { "Status" }, "IX_Course_Status");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Elearning.API.Models.CourseCategory", b =>
                {
                    b.Property<int>("CourseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CourseCategoryId")
                        .HasName("PK__CourseCa__4D67EBB612AEF5B0");

                    b.ToTable("CourseCategory");
                });

            modelBuilder.Entity("Elearning.API.Models.CoursePricingPlan", b =>
                {
                    b.Property<int>("CoursePricingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoursePricingPlanId"));

                    b.Property<int?>("AccessDurationDays")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CoursePricingPlanId")
                        .HasName("PK__CoursePr__A67547648FD6B141");

                    b.HasIndex(new[] { "CourseId" }, "IX_CoursePricingPlan_CourseId");

                    b.ToTable("CoursePricingPlan");
                });

            modelBuilder.Entity("Elearning.API.Models.IssuedCertificate", b =>
                {
                    b.Property<int>("IssuedCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssuedCertificateId"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CertificateTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IssuedCertificateId")
                        .HasName("PK__IssuedCe__FA995DED563281D5");

                    b.HasIndex("CertificateTemplateId");

                    b.HasIndex(new[] { "CourseId" }, "IX_IssuedCertificate_CourseId");

                    b.HasIndex(new[] { "UserId" }, "IX_IssuedCertificate_UserId");

                    b.HasIndex(new[] { "CertificateNumber" }, "UQ__IssuedCe__E384CE0F496D1CB5")
                        .IsUnique();

                    b.ToTable("IssuedCertificate");
                });

            modelBuilder.Entity("Elearning.API.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LessonId")
                        .HasName("PK__Lesson__B084ACD0F4BA978D");

                    b.HasIndex(new[] { "ModuleId" }, "IX_Lesson_ModuleId");

                    b.HasIndex(new[] { "Status" }, "IX_Lesson_Status");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonAttachment", b =>
                {
                    b.Property<int>("LessonAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonAttachmentId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("LessonAttachmentId")
                        .HasName("PK__LessonAt__19A39367B1F36678");

                    b.HasIndex(new[] { "LessonId" }, "IX_LessonAttachment_LessonId");

                    b.ToTable("LessonAttachment");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonContentBlock", b =>
                {
                    b.Property<int>("LessonContentBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonContentBlockId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("LessonContentBlockId")
                        .HasName("PK__LessonCo__68C64C97790CDC0B");

                    b.HasIndex(new[] { "LessonId" }, "IX_LessonContentBlock_LessonId");

                    b.ToTable("LessonContentBlock");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonProgress", b =>
                {
                    b.Property<int>("LessonProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonProgressId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LessonProgressId")
                        .HasName("PK__LessonPr__54391C1C0F05C942");

                    b.HasIndex(new[] { "LessonId" }, "IX_LessonProgress_LessonId");

                    b.HasIndex(new[] { "UserId" }, "IX_LessonProgress_UserId");

                    b.ToTable("LessonProgress");
                });

            modelBuilder.Entity("Elearning.API.Models.MediaFile", b =>
                {
                    b.Property<int>("MediaFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaFileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("MediaFileId")
                        .HasName("PK__MediaFil__E14CB8DB3BCFDFE6");

                    b.HasIndex(new[] { "UploadedByUserId" }, "IX_MediaFile_UserId");

                    b.ToTable("MediaFile");
                });

            modelBuilder.Entity("Elearning.API.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ModuleId")
                        .HasName("PK__Module__2B7477A740FD95D5");

                    b.HasIndex(new[] { "CourseId" }, "IX_Module_CourseId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("Elearning.API.Models.PageContentBlock", b =>
                {
                    b.Property<int>("PageContentBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageContentBlockId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("PageContentBlockId")
                        .HasName("PK__PageCont__E7B6732988AA3720");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex(new[] { "IsActive" }, "IX_PageContentBlock_IsActive");

                    b.HasIndex(new[] { "PageKey" }, "IX_PageContentBlock_PageKey");

                    b.ToTable("PageContentBlock");
                });

            modelBuilder.Entity("Elearning.API.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PassThresholdPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuizId")
                        .HasName("PK__Quiz__8B42AE8EA4FDFAFE");

                    b.HasIndex(new[] { "LessonId" }, "IX_Quiz_LessonId");

                    b.HasIndex(new[] { "ModuleId" }, "IX_Quiz_ModuleId");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAnswerOption", b =>
                {
                    b.Property<int>("QuizAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAnswerOptionId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.HasKey("QuizAnswerOptionId")
                        .HasName("PK__QuizAnsw__6E9E14FFEB46B384");

                    b.HasIndex(new[] { "QuizQuestionId" }, "IX_QuizAnswerOption_QuestionId");

                    b.ToTable("QuizAnswerOption");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ScorePercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ScoreTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptId")
                        .HasName("PK__QuizAtte__F39FDCEDC4F0A150");

                    b.HasIndex(new[] { "QuizId" }, "IX_QuizAttempt_QuizId");

                    b.HasIndex(new[] { "UserId" }, "IX_QuizAttempt_UserId");

                    b.ToTable("QuizAttempt");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("QuizAttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptAnswerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMarkedCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OpenAnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptAnswerId")
                        .HasName("PK__QuizAtte__44A66E3075980595");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex(new[] { "QuizAttemptId" }, "IX_QuizAttemptAnswer_AttemptId");

                    b.HasIndex(new[] { "QuizQuestionId" }, "IX_QuizAttemptAnswer_QuestionId");

                    b.ToTable("QuizAttemptAnswer");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizQuestionId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValueSql("((1.0))");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("QuizQuestionId")
                        .HasName("PK__QuizQues__45E34D3E22D59FF5");

                    b.HasIndex(new[] { "QuizId" }, "IX_QuizQuestion_QuizId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("Elearning.API.Models.SupportMessage", b =>
                {
                    b.Property<int>("SupportMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportMessageId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("int");

                    b.HasKey("SupportMessageId")
                        .HasName("PK__SupportM__1F467E262914FF1F");

                    b.HasIndex("FromUserId");

                    b.HasIndex(new[] { "SupportTicketId" }, "IX_SupportMessage_TicketId");

                    b.ToTable("SupportMessage");
                });

            modelBuilder.Entity("Elearning.API.Models.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportTicketId"));

                    b.Property<int?>("AssignedTutorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupportTicketId")
                        .HasName("PK__SupportT__E064A5F44B05D050");

                    b.HasIndex("AssignedTutorId");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "Status" }, "IX_SupportTicket_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_SupportTicket_UserId");

                    b.ToTable("SupportTicket");
                });

            modelBuilder.Entity("Elearning.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C2D28193D");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Elearning.API.Models.UserCourseAccess", b =>
                {
                    b.Property<int>("UserCourseAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCourseAccessId"));

                    b.Property<DateTime?>("AccessEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AccessStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CoursePricingPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCourseAccessId")
                        .HasName("PK__UserCour__E0F58962964D0B50");

                    b.HasIndex("CoursePricingPlanId");

                    b.HasIndex(new[] { "CourseId" }, "IX_UserCourseAccess_CourseId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserCourseAccess_UserId");

                    b.ToTable("UserCourseAccess");
                });

            modelBuilder.Entity("Elearning.API.Models.UserCourseEnrollment", b =>
                {
                    b.Property<int>("UserCourseEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCourseEnrollmentId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCourseEnrollmentId")
                        .HasName("PK__UserCour__298BB691A9323A7B");

                    b.HasIndex(new[] { "CourseId" }, "IX_UserCourseEnrollment_CourseId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserCourseEnrollment_UserId");

                    b.ToTable("UserCourseEnrollment");
                });

            modelBuilder.Entity("Elearning.API.Models.UserNotification", b =>
                {
                    b.Property<int>("UserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNotificationId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserNotificationId")
                        .HasName("PK__UserNoti__EB298629EC087EB1");

                    b.HasIndex(new[] { "IsRead" }, "IX_UserNotification_IsRead");

                    b.HasIndex(new[] { "UserId" }, "IX_UserNotification_UserId");

                    b.ToTable("UserNotification");
                });

            modelBuilder.Entity("Elearning.API.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId")
                        .HasName("PK__UserProf__9E267F622214AAFF");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserProf__1788CC4D152BB571")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("Elearning.API.Models.Announcement", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "CreatedByUser")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Announcement_User");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Elearning.API.Models.AuditLog", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.Course", b =>
                {
                    b.HasOne("Elearning.API.Models.CourseCategory", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoryId")
                        .HasConstraintName("FK_Course_Category");

                    b.HasOne("Elearning.API.Models.MediaFile", "ThumbnailMedia")
                        .WithMany("Courses")
                        .HasForeignKey("ThumbnailMediaId")
                        .HasConstraintName("FK_Course_ThumbnailMedia");

                    b.HasOne("Elearning.API.Models.User", "TutorUser")
                        .WithMany("TutorCourses")
                        .HasForeignKey("TutorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCategory");

                    b.Navigation("ThumbnailMedia");

                    b.Navigation("TutorUser");
                });

            modelBuilder.Entity("Elearning.API.Models.CoursePricingPlan", b =>
                {
                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("CoursePricingPlans")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CoursePricingPlan_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Elearning.API.Models.IssuedCertificate", b =>
                {
                    b.HasOne("Elearning.API.Models.CertificateTemplate", "CertificateTemplate")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("CertificateTemplateId")
                        .IsRequired()
                        .HasConstraintName("FK_IssuedCertificate_Template");

                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_IssuedCertificate_Course");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("IssuedCertificates")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_IssuedCertificate_User");

                    b.Navigation("CertificateTemplate");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.Lesson", b =>
                {
                    b.HasOne("Elearning.API.Models.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_Module");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonAttachment", b =>
                {
                    b.HasOne("Elearning.API.Models.Lesson", "Lesson")
                        .WithMany("LessonAttachments")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK_LessonAttachment_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonContentBlock", b =>
                {
                    b.HasOne("Elearning.API.Models.Lesson", "Lesson")
                        .WithMany("LessonContentBlocks")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK_LessonContentBlock_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Elearning.API.Models.LessonProgress", b =>
                {
                    b.HasOne("Elearning.API.Models.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK_LessonProgress_Lesson");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LessonProgress_User");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.MediaFile", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "UploadedByUser")
                        .WithMany("MediaFiles")
                        .HasForeignKey("UploadedByUserId")
                        .HasConstraintName("FK_MediaFile_User");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Elearning.API.Models.Module", b =>
                {
                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Module_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Elearning.API.Models.PageContentBlock", b =>
                {
                    b.HasOne("Elearning.API.Models.MediaFile", "MediaFile")
                        .WithMany("PageContentBlocks")
                        .HasForeignKey("MediaFileId")
                        .HasConstraintName("FK_PageContentBlock_Media");

                    b.HasOne("Elearning.API.Models.User", "UpdatedByUser")
                        .WithMany("PageContentBlocks")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_PageContentBlock_User");

                    b.Navigation("MediaFile");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Elearning.API.Models.Quiz", b =>
                {
                    b.HasOne("Elearning.API.Models.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK_Quiz_Lesson");

                    b.HasOne("Elearning.API.Models.Module", "Module")
                        .WithMany("Quizzes")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("FK_Quiz_Module");

                    b.Navigation("Lesson");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAnswerOption", b =>
                {
                    b.HasOne("Elearning.API.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAnswerOptions")
                        .HasForeignKey("QuizQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizAnswerOption_Question");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAttempt", b =>
                {
                    b.HasOne("Elearning.API.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttempt_Quiz");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttempt_User");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAttemptAnswer", b =>
                {
                    b.HasOne("Elearning.API.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizAttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttemptAnswer_Attempt");

                    b.HasOne("Elearning.API.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttemptAnswer_Question");

                    b.HasOne("Elearning.API.Models.QuizAnswerOption", "SelectedOption")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK_QuizAttemptAnswer_Option");

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizQuestion");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizQuestion", b =>
                {
                    b.HasOne("Elearning.API.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK_QuizQuestion_Quiz");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Elearning.API.Models.SupportMessage", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "FromUser")
                        .WithMany("SupportMessages")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SupportMessage_User");

                    b.HasOne("Elearning.API.Models.SupportTicket", "SupportTicket")
                        .WithMany("SupportMessages")
                        .HasForeignKey("SupportTicketId")
                        .IsRequired()
                        .HasConstraintName("FK_SupportMessage_Ticket");

                    b.Navigation("FromUser");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Elearning.API.Models.SupportTicket", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "AssignedTutor")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedTutorId");

                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CourseId");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SupportTicket_User");

                    b.Navigation("AssignedTutor");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Elearning.API.Models.UserCourseAccess", b =>
                {
                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("UserCourseAccesses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseAccess_Course");

                    b.HasOne("Elearning.API.Models.CoursePricingPlan", "CoursePricingPlan")
                        .WithMany("UserCourseAccesses")
                        .HasForeignKey("CoursePricingPlanId")
                        .HasConstraintName("FK_UserCourseAccess_Plan");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("UserCourseAccesses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseAccess_User");

                    b.Navigation("Course");

                    b.Navigation("CoursePricingPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.UserCourseEnrollment", b =>
                {
                    b.HasOne("Elearning.API.Models.Course", "Course")
                        .WithMany("UserCourseEnrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseEnrollment_Course");

                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("UserCourseEnrollments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseEnrollment_User");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.UserNotification", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.UserProfile", b =>
                {
                    b.HasOne("Elearning.API.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Elearning.API.Models.UserProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserProfile_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elearning.API.Models.CertificateTemplate", b =>
                {
                    b.Navigation("IssuedCertificates");
                });

            modelBuilder.Entity("Elearning.API.Models.Course", b =>
                {
                    b.Navigation("CoursePricingPlans");

                    b.Navigation("IssuedCertificates");

                    b.Navigation("Modules");

                    b.Navigation("SupportTickets");

                    b.Navigation("UserCourseAccesses");

                    b.Navigation("UserCourseEnrollments");
                });

            modelBuilder.Entity("Elearning.API.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Elearning.API.Models.CoursePricingPlan", b =>
                {
                    b.Navigation("UserCourseAccesses");
                });

            modelBuilder.Entity("Elearning.API.Models.Lesson", b =>
                {
                    b.Navigation("LessonAttachments");

                    b.Navigation("LessonContentBlocks");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Elearning.API.Models.MediaFile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("PageContentBlocks");
                });

            modelBuilder.Entity("Elearning.API.Models.Module", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Elearning.API.Models.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAnswerOption", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizAttempt", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("Elearning.API.Models.QuizQuestion", b =>
                {
                    b.Navigation("QuizAnswerOptions");

                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("Elearning.API.Models.SupportTicket", b =>
                {
                    b.Navigation("SupportMessages");
                });

            modelBuilder.Entity("Elearning.API.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("AssignedTickets");

                    b.Navigation("AuditLogs");

                    b.Navigation("IssuedCertificates");

                    b.Navigation("LessonProgresses");

                    b.Navigation("MediaFiles");

                    b.Navigation("PageContentBlocks");

                    b.Navigation("QuizAttempts");

                    b.Navigation("SupportMessages");

                    b.Navigation("SupportTickets");

                    b.Navigation("TutorCourses");

                    b.Navigation("UserCourseAccesses");

                    b.Navigation("UserCourseEnrollments");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
